spring.application.name=movibus
spring.datasource.url=jdbc:postgresql://localhost:5432/dBMoviBus
spring.datasource.username=postgres
spring.datasource.password=sasa

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false
spring.jackson.serialization.fail-on-empty-beans=false
server.port=8080